### ISSUE TITLE
Add a README, LICENSE, and CHANGELOG to this repo

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/code-generator#1]

**Comment by sttts** [comment]
The first two are added in https://github.com/kubernetes/code-generator/pull/3. About the CHANGELOG we should talk for all repos we publish. Even client-go is not filled with useful information. We should probably generally refer to the kube changelog and maybe tag/sort that in a way that our published repos get their own section we can link to.

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/test-infra/issues/5843, https://github.com/kubernetes/client-go/pull/341.
