### ISSUE TITLE
Support different plural forms

### ISSUE THREAD

**Issue by alewitt2** [kubernetes/code-generator#101]
#53 should not be a feature request, it should be a bug. The same problem was reported in kubernetes/kubernetes#51639 and addressed in kubernetes/kubernetes#50012

We have the same issue as #53 for our CRDs, where we use a different plural than just an `s` on the end of the singular. This wasnt an issue until one of our users wanted to use this code generator. https://github.com/razee-io/RemoteResourceS3/issues/80. The work around as mentioned in #53 works, but is not how one would expect a code generator to behave.

**Comment by nikhita** [comment]
@dvasilen you can use the `plural-exceptions` flag for this:

https://github.com/kubernetes/code-generator/blob/7baaea6316a654efa04671651b591fa6d87069b5/cmd/client-gen/args/args.go#L52-L54

https://github.com/kubernetes/code-generator/blob/7baaea6316a654efa04671651b591fa6d87069b5/cmd/client-gen/args/args.go#L86

**Comment by alewitt2** [comment]
@dvasilen does this work as a solution for you? can we close this issue out?

**Comment by dvasilen** [comment]
@alewitt2 yes, please close this issue, thanks

**Comment by rgowrishankar** [comment]
@nikhita @dvasilen @alewitt2 I tried to use the `plural-extensions` with FeatureFlagSetLD CRD which has the same plural issue
https://github.com/razee-io/FeatureFlagSetLD/blob/master/kubernetes/FeatureFlagSetLD/resource.yaml#L303-L310
by adding
`--plural-exceptions={"FeatureFlagSetLD:FeatureFlagSetsLD"}`
to the client-gen binary invocation but it is still generating the client-set with `FeatureFlagSetLDs` as the plural instead of `FeatureFlagSetsLD`
My CRD definition is
```
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type FeatureFlagSetLD struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeatureFlagSetLdSpec `json:"spec"`
	Data              map[string]string    `json:"data"`
	Status            map[string]string    `json:"status"`
}
```

I am using codegen version 1.18. If I pass in some random string for `--plural-exceptions` did does segfault in the correct piece of code, so the parameter is being parsed but I don't know why it is not getting used (does it need some additional tags in the go code CRD?).

**Comment by lxd5866** [comment]
> @nikhita @dvasilen @alewitt2 I tried to use the `plural-extensions` with FeatureFlagSetLD CRD which has the same plural issue https://github.com/razee-io/FeatureFlagSetLD/blob/master/kubernetes/FeatureFlagSetLD/resource.yaml#L303-L310 by adding `--plural-exceptions={"FeatureFlagSetLD:FeatureFlagSetsLD"}` to the client-gen binary invocation but it is still generating the client-set with `FeatureFlagSetLDs` as the plural instead of `FeatureFlagSetsLD` My CRD definition is
> 
> ```
> // +genclient
> // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
> type FeatureFlagSetLD struct {
> 	metav1.TypeMeta   `json:",inline"`
> 	metav1.ObjectMeta `json:"metadata,omitempty"`
> 	Spec              FeatureFlagSetLdSpec `json:"spec"`
> 	Data              map[string]string    `json:"data"`
> 	Status            map[string]string    `json:"status"`
> }
> ```
> 
> I am using codegen version 1.18. If I pass in some random string for `--plural-exceptions` did does segfault in the correct piece of code, so the parameter is being parsed but I don't know why it is not getting used (does it need some additional tags in the go code CRD?).
> 
> Snippet of generated code
> 
> ```
> func (c *featureFlagSetLDs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.FeatureFlagSetLD, err error) {
> 	result = &v1alpha2.FeatureFlagSetLD{}
> 	err = c.client.Get().
> 		Namespace(c.ns).
> 		Resource("featureflagsetlds").
> 		Name(name).
> 		VersionedParams(&options, scheme.ParameterCodec).
> 		Do(ctx).
> 		Into(result)
> 	return
> }
> ```

--plural-exceptions="FeatureFlagSetLD:FeatureFlagSetsLD" maybe ok
