### ISSUE TITLE
deepcopy-gen writes to the wrong directory with v2-style semver module version

### ISSUE THREAD

**Issue by abayer** [kubernetes/code-generator#102]
I'm moving a project to be semver-compliant in its go module versioning, and have run into a couple issues with code gen here (I'll be opening another issue for a problem common to `client-gen` and `informer-gen`). The project in question already has `v2.x.x` tags, so we're changing the module from `github.com/jenkins-x/jx` to `github.com/jenkins-x/jx/v2` and leaving the `pkg` layout on disk the same.

When I run `deepcopy-gen --output-base /Users/abayer/go/src --go-header-file /Users/abayer/go/src/github.com/jenkins-x/jx/custom-boilerplate.go.txt --input-dirs github.com/jenkins-x/jx/v2/pkg/apis/jenkins.io/v1 -O zz_generated.deepcopy --bounding-dirs github.com/jenkins-x/jx/v2/pkg/apis`, it generates the right `zz_generated.deepcopy.go`, but it writes it to `v2/pkg/apis/jenkins.io/v1`, not `pkg/apis/jenkins.io/v1`. I can't figure out an option to control the root directory under which it outputs. I've worked around this for the moment, but it'd be nice to not need to. =)

I'm not 100% sure this is the right repo to open this in, since most of the deepcopy logic appears to be in gengo, so let me know if I should move this. Thanks!

**Comment by rawlingsj** [comment]
I just hit this as well on a different repo.  Same story, using semver go modules:

i.e. example go.mod file __note the /v1 at the end of the first line...
```go.mod
module github.com/foo/bar/v1

go 1.15

require (
  ...
)
```

included in the repo:
```
pkg/
├── apis
    └── foo
        └── v1
            ├── doc.go
            ├── register.go
            └── types.go
```

./hack/update-codegen.sh
```
bash "${CODEGEN_PKG}"/generate-groups.sh "deepcopy,client,informer,lister,openapi" \
  github.com/foo/bar/pkg/client github.com/foo/bar/v1/pkg/apis \
  foo.io:v1 \
  --output-base "$(dirname "${BASH_SOURCE[0]}")/../../../.." 
```

Generates a file...

`pkg/client/clientset/versioned/clientset.go`
```go
package versioned

import (
	"fmt"

	foov1 "github.com/foo/bar/pkg/client/clientset/versioned/typed/foo.io/v1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)
```
this causes issues because the import should include the semver module version `v1` from the go.mod file above
i.e. should look like this..
```go
package versioned

import (
	"fmt"

	foov1 "github.com/foo/bar/v1/pkg/client/clientset/versioned/typed/foo.io/v1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)
```
