### ISSUE TITLE
code-generator don't generate clientset, informer and lister

### ISSUE THREAD

**Issue by JaneLiuL** [kubernetes/code-generator#106]
Question: 
When I use code-generator try to generate the clienset, informer and lister, it does not tell me any issue, but when I check the generate folder, it only have clientset, and the content is almost empty
![image](https://user-images.githubusercontent.com/56822274/80273118-29408500-8702-11ea-91d0-37358dd2a7d5.png)

My *_type.go file as below:
package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// +k8s:openapi-gen=true
// +resource:path=containersets

// +kubebuilder:object:root=true

// Appmgmt is the Schema for the appmgmts API
type Appmgmt struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AppmgmtSpec   `json:"spec,omitempty"`
	Status AppmgmtStatus `json:"status,omitempty"`
}

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// AppmgmtSpec defines the desired state of Appmgmt
type AppmgmtSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Foo is an example field of Appmgmt. Edit Appmgmt_types.go to remove/update
	// Foo string `json:"foo,omitempty"`
	FindNamespace					string		`json:"findnamespace"`	
	Image							string  	`json:"image"`
	Env	    						[]Env		`json:"env"`	
	Ports    						int 		`json:"ports"`
	ImagePullSecret 			 	string	`json:"imagePullSecret"`
}

type Env struct {
	Name string `json:"name"`
}
// AppmgmtStatus defines the observed state of Appmgmt
type AppmgmtStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	TestStatus	string	 `json:"testStatus"`
}

// +kubebuilder:object:root=true

// AppmgmtList contains a list of Appmgmt
type AppmgmtList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Appmgmt `json:"items"`
}

var (    
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: "appmgmt", Version: "v1beta1"}
  
	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion})

func init() {
	SchemeBuilder.Register(&Appmgmt{}, &AppmgmtList{})
}

Environment as below:
$go version
go version go1.13.8 linux/amd64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

$go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/installation/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/installation/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build867010754=/tmp/go-build -gno-record-gcc-switches"

**Comment by ezliuja** [comment]
![image](https://user-images.githubusercontent.com/56822274/80273222-fc40a200-8702-11ea-8df4-2f26117255fd.png)
This is what have been generate, it is very strange, and when I check file generated/clientset/versioned/clientset.go only have one word "package versioned"

**Comment by antoineco** [comment]
Code generators write in a directory relative to `$GOPATH/src`.
In your case: `$GOPATH/src/appmgmt-operator/generated/appmgmt-operator/api`.

**Comment by ezliuja** [comment]
yes, but the strange thing is , it only generate the clientset, and the clientset code is only have something like "package clientset", I don't know where's wrong, even it said generate informer success, but still don't have this part code

-- generated
|   `-- clientset
|       `-- versioned
|           |-- clientset.go
|           |-- doc.go
|           |-- fake
|           |   |-- clientset_generated.go
|           |   |-- doc.go
|           |   `-- register.go
|           |-- scheme
|           |   |-- doc.go
|           |   `-- register.go
|           `-- typed
|               `-- appmgmt
|                   `-- v1alpha1
|                       |-- appmgmt_client.go
|                       |-- doc.go
|                       |-- fake
|                       |   |-- doc.go
|                       |   `-- fake_appmgmt_client.go
|                       `-- generated_expansion.go
|-- go.mod

**Comment by antoineco** [comment]
Is your code available somewhere?

**Comment by wubo0067** [comment]
I had the same problem, using an operator-sdk.

**Comment by ezliuja** [comment]
If you use operator-sdk, and use the code-generate to generate the clientset, informers, then you will get fail.
But if you only write apis_types.go by yourself in a empty project, then you can use the code-generate to generate the clientset, informers and so on

**Comment by gabrik** [comment]
Hi all,

I'm having the exact same problem.

The code is available here: https://github.com/gabrik/example-custom-controller 

If I run the `code-generator` without passing `--output-base` it complains about not finding `boilerplate.go.txt` (even if the file is there)
```
Failed loading boilerplate: open k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
```

Otherwise, it just generates the `versioned` files that are almost empty.

I've also checked in `$GOPATH/src/github.com/gabrik/example-custom-controller` but nothing there.


I'm doing it wrong?

**Comment by antoineco** [comment]
@gabrik because by default code generators try to read `${GOPATH}/src/k8s.io/code-generator/hack/boilerplate.go.txt`. Notice the $GOPATH in there. That means you have to manually clone the code-generator repository at this location on your machine.

There is a better and simpler approach though:

I see you have your own boilerplate file in the repo you linked. That means you have to reference it manually by passing `--go-header-file hack/boilerplate.go.txt` at the end of [this line](https://github.com/gabrik/example-custom-controller/blob/d6cffb26910c256ad4f63736f03a6813174bed1c/hack/update-codegen.sh#L19).

Here is an example: https://github.com/knative-sandbox/eventing-gitlab/blob/602b94319985c830fa2a9ba978e3f3c5886a760b/hack/update-codegen.sh#L34-L37

**Comment by gabrik** [comment]
Thank you @antoineco 
I indeed added that parameter and now it works.

**Comment by onkarbanerjee** [comment]
This issue is till there for me, can anyone help?

**Comment by antoineco** [comment]
@onkarbanerjee yes, if you describe your issue I can try to help.

Please provide snippets of your scripts, the structure of your project, and the errors you're seeing.

**Comment by onkarbanerjee** [comment]
@antoineco Thanks for your response. Here is what I am trying to do.

This is my code directory structure
![image](https://user-images.githubusercontent.com/46961494/113926967-7c73f080-980a-11eb-97df-2ea40304cb74.png)

This is my types.go
```
// +genclient

// +genclient:noStatus

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec DatabaseSpec `json:"spec"`
}

// DatabaseSpec is the spec for a Foo resource
type DatabaseSpec struct {
	User     string `json:"user"`
	Password string `json:"password"`
	Encoding string `json:"encoding,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items []Database `json:"items"`
}
```

This is my doc.go
```
// +k8s:deepcopy-gen=package
// Package v1 is the v1 version of the API.
// +groupName=example.com
package v1
```

I am running the script like below:
![image](https://user-images.githubusercontent.com/46961494/113927135-b5ac6080-980a-11eb-8a1f-8bf12026c99a.png)

But there are no files created ever

**Comment by antoineco** [comment]
@onkarbanerjee chances are that your code was generated in `$GOPATH/src/github.com/onkarbanerjee/crd-code`, and not in your current project's directory.

**Comment by onkarbanerjee** [comment]
@antoineco No code generated.
![image](https://user-images.githubusercontent.com/46961494/113980633-5b3fee00-9864-11eb-919e-0f5b2682f692.png)

**Comment by antoineco** [comment]
Your screenshot doesn't show `pkg/client`.

**Comment by onkarbanerjee** [comment]
@antoineco It only has the clientset folder and the files in them are mostly empty.
![image](https://user-images.githubusercontent.com/46961494/113982957-0356b680-9867-11eb-9898-6caaf23ff943.png)

**Comment by zq-david-wang** [comment]
append "-v 10" at the end of your command, it should tell where is wrong.

The tool would exit with success code when it has done nothing.......

**Comment by onkarbanerjee** [comment]
@zq-david-wang  It us unable to import the package it seems.
![image](https://user-images.githubusercontent.com/46961494/114018867-580c2880-988b-11eb-92f7-27edf6393639.png)

**Comment by antoineco** [comment]
@onkarbanerjee this seems like a misconfigured Go project or Go toolchain to me. This goes beyond the topic of this discussion, but here are two ways to fix this:
* If your Go project uses modules, make sure `go.mod` starts with the line `module github.com/onkarbanerjee/crd-code`
* If it doesn't, please refer to [Module-aware commands](https://golang.org/ref/mod#mod-commands) in the Go documentation

**Comment by harryyann** [comment]
Hello,there. I have the problem something similar. I use the shell script to generate code, but I got only one clientset folder and which is almost empty. There is no any Errors or Warnings.The code I used is just the same as the [sample-controller](https://github.com/kubernetes/sample-controller).



My project is just like this:
```
root: /sameple-controller ls
apis  controller.go  go.mod  go.sum  hack  main.go  vendor
```
```
root: /sameple-controller# tree apis
apis
└── samplecontroller
    ├── register.go
    └── v1alpha1
        ├── doc.go
        ├── register.go
        └── types.go

2 directories, 4 files
```
the shell script to generate code:

```
root:/sameple-controller# cat hack/update-codegen.sh 
set -o errexit
set -o nounset
set -o pipefail

# generate the code with:
# --output-base    because this script should also be able to run inside the vendor dir of
#                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
#                  instead of the $GOPATH directly. For normal projects this can be dropped.
../vendor/k8s.io/code-generator/generate-groups.sh \
  "deepcopy,client,informer,lister" \
  sameple-controller/generated \
  sameple-controller/apis \
  samplecontroller:v1alpha1 \
  --go-header-file $(pwd)/boilerplate.go.txt \
  --output-base $(pwd)/../../
```

My go.mod file:
```
root:/sameple-controller# cat go.mod 
// This is a generated file. Do not edit directly.

module k8s.io/sample-controller

go 1.16

require (
        k8s.io/apimachinery v0.21.0
        k8s.io/code-generator v0.21.0
)

replace (
        k8s.io/apimachinery => k8s.io/apimachinery v0.21.0
        k8s.io/code-generator => k8s.io/code-generator v0.21.0
)

```
The response is no Erroers

```
root:/sameple-controller/hack# bash update-codegen.sh 
Generating deepcopy funcs
Generating clientset for samplecontroller:v1alpha1 at sameple-controller/generated/clientset
Generating listers for samplecontroller:v1alpha1 at sameple-controller/generated/listers
Generating informers for samplecontroller:v1alpha1 at sameple-controller/generated/informers
```
And the generated folder only has a clientset folder in it, and its just almost empty:
```
root@cld-dnode2-1091:/home/wb.yanghairui/cluster-inspector-go/cmd/sameple-controller# tree generated/
generated/
└── clientset
    └── versioned
        ├── clientset.go
        ├── doc.go
        ├── fake
        │   ├── clientset_generated.go
        │   ├── doc.go
        │   └── register.go
        ├── scheme
        │   ├── doc.go
        │   └── register.go
        └── typed
            └── samplecontroller
                └── v1alpha1
                    ├── doc.go
                    ├── fake
                    │   ├── doc.go
                    │   └── fake_samplecontroller_client.go
                    ├── generated_expansion.go
                    └── samplecontroller_client.go

8 directories, 12 files

```
I don't realy know what's the problem is.

**Comment by pickfire** [comment]
@harryyann Legacy, `$GOPATH`...

**Comment by RookiesBoy** [comment]
> Hello,there. I have the problem something similar. I use the shell script to generate code, but I got only one clientset folder and which is almost empty. There is no any Errors or Warnings.The code I used is just the same as the [sample-controller](https://github.com/kubernetes/sample-controller).
> 
> My project is just like this:
> 
> ```
> root: /sameple-controller ls
> apis  controller.go  go.mod  go.sum  hack  main.go  vendor
> ```
> 
> ```
> root: /sameple-controller# tree apis
> apis
> └── samplecontroller
>     ├── register.go
>     └── v1alpha1
>         ├── doc.go
>         ├── register.go
>         └── types.go
> 
> 2 directories, 4 files
> ```
> 
> the shell script to generate code:
> 
> ```
> root:/sameple-controller# cat hack/update-codegen.sh 
> set -o errexit
> set -o nounset
> set -o pipefail
> 
> # generate the code with:
> # --output-base    because this script should also be able to run inside the vendor dir of
> #                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
> #                  instead of the $GOPATH directly. For normal projects this can be dropped.
> ../vendor/k8s.io/code-generator/generate-groups.sh \
>   "deepcopy,client,informer,lister" \
>   sameple-controller/generated \
>   sameple-controller/apis \
>   samplecontroller:v1alpha1 \
>   --go-header-file $(pwd)/boilerplate.go.txt \
>   --output-base $(pwd)/../../
> ```
> 
> My go.mod file:
> 
> ```
> root:/sameple-controller# cat go.mod 
> // This is a generated file. Do not edit directly.
> 
> module k8s.io/sample-controller
> 
> go 1.16
> 
> require (
>         k8s.io/apimachinery v0.21.0
>         k8s.io/code-generator v0.21.0
> )
> 
> replace (
>         k8s.io/apimachinery => k8s.io/apimachinery v0.21.0
>         k8s.io/code-generator => k8s.io/code-generator v0.21.0
> )
> ```
> 
> The response is no Erroers
> 
> ```
> root:/sameple-controller/hack# bash update-codegen.sh 
> Generating deepcopy funcs
> Generating clientset for samplecontroller:v1alpha1 at sameple-controller/generated/clientset
> Generating listers for samplecontroller:v1alpha1 at sameple-controller/generated/listers
> Generating informers for samplecontroller:v1alpha1 at sameple-controller/generated/informers
> ```
> 
> And the generated folder only has a clientset folder in it, and its just almost empty:
> 
> ```
> root@cld-dnode2-1091:/home/wb.yanghairui/cluster-inspector-go/cmd/sameple-controller# tree generated/
> generated/
> └── clientset
>     └── versioned
>         ├── clientset.go
>         ├── doc.go
>         ├── fake
>         │   ├── clientset_generated.go
>         │   ├── doc.go
>         │   └── register.go
>         ├── scheme
>         │   ├── doc.go
>         │   └── register.go
>         └── typed
>             └── samplecontroller
>                 └── v1alpha1
>                     ├── doc.go
>                     ├── fake
>                     │   ├── doc.go
>                     │   └── fake_samplecontroller_client.go
>                     ├── generated_expansion.go
>                     └── samplecontroller_client.go
> 
> 8 directories, 12 files
> ```
> 
> I don't realy know what's the problem is.

I have the same problem

**Comment by JesseStutler** [comment]
@harryyann I have the same problem.Only clientset was generated.

**Comment by naduvat** [comment]
@harryyann I was facing a similar issue. Mine was because the tags were not set correctly in types.go. i had a few empty lines between the comment and the struct definition. The gengo parser was skipping this saying the doesn't need a client code generation 

The below is what is had initially.

```// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object



type PolicyDefinition struct {
    metav1.TypeMeta             `json:",inline"`
    // +optional
    metav1.ObjectMeta           `json:"metadata"`
    Name string                 `json:"name"`
}
```

I change it as follows to get it working 

```
// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type PolicyDefinition struct {
    metav1.TypeMeta             `json:",inline"`
    // +optional
    metav1.ObjectMeta           `json:"metadata"`
    Name string                 `json:"name"`
}
```

There were some issues with the directory structure also. I felt instead of ironing out the supported directory structure it is easier to make a directory structure which the generator expect. 

I have the structure as follows from the workspace root 
```
 github.com
        └── user
            └── repo
                ├── go.mod
                ├── go.sum
                └── pkg
                    └── apis
                        └── k8s.crd.io
                            └── v1alpha1
                                ├── doc.go
                                ├── register.go
                                └── types.go
```

The tree is mimicking the module name github.com/user/repo

The generator is executed from the module directory github.com/user/repo

```
$GEN/generate-groups.sh all $MODULE/pkg/client $MODULE/pkg/apis "k8s.crd.io:v1alpha1" -h $GEN/hack/boilerplate.go.txt -o $WSROOT --go-header-file $GEN/hack/boilerplate.go.txt


GEN=<path to code-generator>
MODULE=<module name = github.com/user/repo>
WSROOT=<root of the workspace>
```

I have uploaded a sample code here incase needed [https://github.com/naduvat/k8s-codegen-basic](https://github.com/naduvat/k8s-codegen-basic)

**Comment by gorexlv** [comment]
Same problem, only clientset package generated, and no error/warning log outputs.
Is there anyone resolved this problem?

**Comment by pickfire** [comment]
I resolved it. Issue related to `$GOPATH` but I don't recall how.

**Comment by seven-yu** [comment]
> I have the same problem.Only clientset was generated.

me too !!!

**Comment by zonzpoo** [comment]
> > I have the same problem.Only clientset was generated.
> 
> me too !!!

./vendor/k8s.io/code-generator/generate-groups.sh "all" "./pkg/generated" "./pkg/apis" "samplecrd:v1" -o "./"  --go-header-file "./hack/boilerplate.go.txt"

this is ok for me

**Comment by droslean** [comment]
Is there any solution to this problem? It seems that the tool is generating files with only the package and the boilerplate included. 

Is anyone taking care of this issue?

@dims ?

**Comment by devops007** [comment]
@droslean 
I have solved this problem， add ”-v 10“ flag， and the following errors were found：
```
unable to import "api/crd.k8s.xxx.com/v1": open /Users/westos/Workspace/gopath/src/qpa/vendor/api/crd.k8s.xxx.com/v1: no such file or directory
```

so copy api/crd.k8s.xxx.com/v1 to ./vendor

```
➜  tree generated -L 1
generated
├── clientset
├── informers
└── listers

```

**Comment by gxglls** [comment]
> @droslean
> I have solved this problem， add ”-v 10“ flag， and the following errors were found：
> 
> ```
> unable to import "api/crd.k8s.xxx.com/v1": open /Users/westos/Workspace/gopath/src/qpa/vendor/api/crd.k8s.xxx.com/v1: no such file or directory
> ```
> 
> so copy api/crd.k8s.xxx.com/v1 to ./vendor
> 
> ```
> ➜  tree generated -L 1
> generated
> ├── clientset
> ├── informers
> └── listers
> ```

thanks, gave me a great help

**Comment by bingws** [comment]
GO111MODULE=off

**Comment by YTGhost** [comment]
@onkarbanerjee Hello, I want to ask you if you have solved this problem? I have encountered the same mistake as you

**Comment by senglezou** [comment]
> > > I have the same problem.Only clientset was generated.
> > 
> > 
> > me too !!!
> 
> workdir：
> 
> ```
> ├── go.mod
> ├── go.sum
> ├── hack
> │   ├── boilerplate.go.txt
> │   ├── tools.go
> │   ├── update-codegen.sh
> ├── pkg
> │   └── apis
> │       └── samplecrd
> │           ├── register.go
> │           └── v1
> │               ├── doc.go
> │               ├── register.go
> │               └── types.go
> └── vendor
>     ├── github.com
>      ...
> ```
> 
> ./vendor/k8s.io/code-generator/generate-groups.sh "all" "./pkg/generated" "./pkg/apis" "samplecrd:v1" -o "./" --go-header-file "./hack/boilerplate.go.txt"
> 
> this is ok for me

@zonzpoo This worked for me! Thank you so much. 

Also for anyone still having issues, I had to also upgrade Go1.15 to Go1.17.

**Comment by Aisuko** [comment]
I hit the same type issue. And I fixed this in this way(I guess it's not a solution, due to everytime go mod tidy will replace the dependencies in vendor),

```
#!/usr/bin/env bash


set -o errexit
set -o nounset
set -o pipefail


GENERATED_PACKAGE_ROOT="<your group>"
OPERATOR_PACKAGE_ROOT="${GENERATED_PACKAGE_ROOT}/<operator-name>"
SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
TARGET_CODE_DIR=${1-${SCRIPT_ROOT}/pkg}
CODEGEN_PKG=${CODEGEN_PKG:-$(cd "${SCRIPT_ROOT}"; ls -d -1 ./vendor/k8s.io/code-generator 2>/dev/null || echo ../code-generator)}


cleanup() {
    rm -rf "${GENERATED_PACKAGE_ROOT}"
}
trap "cleanup" EXIT SIGINT

# generate the code with:
# --output-base    because this script should also be able to run inside the vendor dir of
#                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
#                  instead of the $GOPATH directly. For normal projects this can be dropped.
bash "${CODEGEN_PKG}"/generate-groups.sh all \
  "${OPERATOR_PACKAGE_ROOT}"/pkg/generated "${OPERATOR_PACKAGE_ROOT}"/pkg/apis \
  <you group>:v1 \
  --go-header-file "${SCRIPT_ROOT}"/hack/custom-boilerplate.go.txt -v 10

cp -r "${OPERATOR_PACKAGE_ROOT}"/pkg/* "${TARGET_CODE_DIR}"

cleanup
```

And add `GOPATH=$(go env GOPATH)` to `generate-groups.sh` which in vendor dependencies `vendor/k8s.io/code-generator/generate-groups.sh`

```
GENS="$1"
OUTPUT_PKG="$2"
APIS_PKG="$3"
GROUPS_WITH_VERSIONS="$4"
shift 4

(
  # To support running this script from anywhere, we have to first cd into this directory
  # so we can install the tools.
  cd "$(dirname "${0}")"
  go install ./cmd/{defaulter-gen,client-gen,lister-gen,informer-gen,deepcopy-gen}
)
GOPATH=$(go env GOPATH) // Here we add this https://github.com/kubernetes/kubernetes/pull/85302
function codegen::join() { local IFS="$1"; shift; echo "$*"; }
```

**Comment by chenyangxueHDU** [comment]
> I change it as follows to get it working

it works!

**Comment by AaronMegs** [comment]
> > > I have the same problem.Only clientset was generated.
> > 
> > 
> > me too !!!
> 
> workdir：
> 
> ```
> ├── go.mod
> ├── go.sum
> ├── hack
> │   ├── boilerplate.go.txt
> │   ├── tools.go
> │   ├── update-codegen.sh
> ├── pkg
> │   └── apis
> │       └── samplecrd
> │           ├── register.go
> │           └── v1
> │               ├── doc.go
> │               ├── register.go
> │               └── types.go
> └── vendor
>     ├── github.com
>      ...
> ```
> 
> ./vendor/k8s.io/code-generator/generate-groups.sh "all" "./pkg/generated" "./pkg/apis" "samplecrd:v1" -o "./" --go-header-file "./hack/boilerplate.go.txt"
> 
> this is ok for me

Thanks, It's helpful

**Comment by AaronMegs** [comment]
> > > > I have the same problem.Only clientset was generated.
> > > 
> > > 
> > > me too !!!
> > 
> > 
> > workdir：
> > ```
> > ├── go.mod
> > ├── go.sum
> > ├── hack
> > │   ├── boilerplate.go.txt
> > │   ├── tools.go
> > │   ├── update-codegen.sh
> > ├── pkg
> > │   └── apis
> > │       └── samplecrd
> > │           ├── register.go
> > │           └── v1
> > │               ├── doc.go
> > │               ├── register.go
> > │               └── types.go
> > └── vendor
> >     ├── github.com
> >      ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ./vendor/k8s.io/code-generator/generate-groups.sh "all" "./pkg/generated" "./pkg/apis" "samplecrd:v1" -o "./" --go-header-file "./hack/boilerplate.go.txt"
> > this is ok for me
> 
> Thanks, It's helpful

Also can change
```sh
bash "${CODEGEN_PKG}"/generate-groups.sh "deepcopy,client,informer,lister" \
  k8s.io/sample-controller/pkg/generated k8s.io/sample-controller/pkg/apis \
  samplecontroller:v1alpha1 \
  --output-base "$(dirname "${BASH_SOURCE[0]}")/../../.." \
  --go-header-file "${SCRIPT_ROOT}"/hack/boilerplate.go.txt
```
to 
```sh
bash "${CODEGEN_PKG}"/generate-groups.sh "deepcopy,client,informer,lister" \
  ./pkg/client ./pkg/apis \
  samplecrd:v1alpha1 \
  --output-base "${SCRIPT_ROOT}" \
  --go-header-file "${SCRIPT_ROOT}"/hack/boilerplate.go.txt
```
This is ok for me

**Comment by hackeren** [comment]
before you call update-codegen.sh, try to run 'go mod vendor' If you have used vendor

**Comment by devdattakulkarni** [comment]
> export GO111MODULE=off

@bingws 💯 Setting GO111MODULE=off worked for me. 👍

**Comment by THMAIL** [comment]
> 
you are my angel！！！！I love you！！！！！！！！！！！！！！！！！

**Comment by zffocussss** [comment]
It is still not resolved when integrated with code-generator.
