### ISSUE TITLE
getting compile error about typed client when try to access generated clientset

### ISSUE THREAD

**Issue by marghahay** [kubernetes/code-generator#108]
I am trying to use code-generator to create a client to access a custom resource called Account.
I used code-generator to generate a clientset.  all the generated typed client and everything look ok and the same as k8s sample-controller example code.  However when i import my acctclientset like below to try to access the generated clientset, i get compile error for the account.go, which is the typed client code-gen created.  I am new to go and k8s, i have googled everywhere but still can't figure out how to fix the error.  has anyone encountered this issue or have any suggestion? thanks.

Here is how i added dep:
go get k8s.io/code-generator

***************
my code:
***************
import (
acctclientset "github.xxx.com/example/pkg/apis/client/clientset/versioned"
...
)

func getAccount() {
	cfg, err1 := clientcmd.BuildConfigFromFlags("", "")
	if err1 != nil {
		glog.Fatalf("Can not get kubernetes config: %v", err1)
	}

	exampleClient, err := acctclientset.NewForConfig(cfg)
	if err != nil {
		klog.Fatalf("Error building example clientset: %s", err.Error())
	}
	glog.Infof("The example client is: %v", exampleClient)
}
---------------------------------------------

******************
error i am getting:
******************
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o output/goexecutable .
pkg/apis/client/clientset/versioned/typed/acct/v1alpha1/account.go:71:5: too many arguments in call to c.client.Get().Resource("accounts").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
	have (context.Context)
	want ()
pkg/apis/client/clientset/versioned/typed/acct/v1alpha1/account.go:87:5: too many arguments in call to c.client.Get().Resource("accounts").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Do
	have (context.Context)
	want ()
pkg/apis/client/clientset/versioned/typed/acct/v1alpha1/account.go:103:8: too many arguments in call to c.client.Get().Resource("accounts").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Watch
	have (context.Context)
	want ()
pkg/apis/client/clientset/versioned/typed/acct/v1alpha1/account.go:113:5: too many arguments in call to c.client.Post().Resource("accounts").VersionedParams(&opts, scheme.ParameterCodec).Body(account).Do
	have (context.Context)
	want ()

...

**Comment by bhavyanshu** [comment]
How did you fix this? I am seeing the same issue.

**Comment by marghahay** [comment]
i found two ways to fix the problem:

1. after code generated, manually modify the generated files for the compile errors.
for me, I found there were 2 files need to modify.

ex:  in sample-controller (https://github.com/kubernetes/sample-controller), you will need to manually remove every "ctx context.Context" in the following two files:
/pkg/generated/clientset/versioned/typed/samplecontroller/v1alpha1//foo.go
/pkg/generated/clientset/versioned/typed/samplecontroller/v1alpha1/fake/fake_foo.go

For example, change from: 
Create(ctx context.Context, foo *v1alpha1.Foo, opts v1.CreateOptions) (*v1alpha1.Foo, error)
to:
Create(foo *v1alpha1.Foo, opts v1.CreateOptions) (*v1alpha1.Foo, error)	

2. use an older version of k8s.io/code-generator to generate the code.  With an older version of code-generator, the generated files don't have "ctx context.Context" and there is no compile error for me.  I am currently using this method as a workaround.

**Comment by marghahay** [comment]
> @marghahay How did you fix this? I am seeing the same issue.

i found two ways to fix the problem:

    after code generated, manually modify the generated files for the compile errors.
    for me, I found there were 2 files need to modify.

ex: in sample-controller (https://github.com/kubernetes/sample-controller), you will need to manually remove every "ctx context.Context" in the following two files:
/pkg/generated/clientset/versioned/typed/samplecontroller/v1alpha1//foo.go
/pkg/generated/clientset/versioned/typed/samplecontroller/v1alpha1/fake/fake_foo.go

For example, change from:
Create(ctx context.Context, foo *v1alpha1.Foo, opts v1.CreateOptions) (*v1alpha1.Foo, error)
to:
Create(foo *v1alpha1.Foo, opts v1.CreateOptions) (*v1alpha1.Foo, error)

    use an older version of k8s.io/code-generator to generate the code. With an older version of code-generator, the generated files don't have "ctx context.Context" and there is no compile error for me. I am currently using this method as a workaround.


> @marghahay How did you fix this? I am seeing the same issue.
