### ISSUE TITLE
Error: Failed making a parser: unable to add directory

### ISSUE THREAD

**Issue by Alexbyy** [kubernetes/code-generator#114]
I downloaded the project of sample-controller on the official website,then I renamed the project "fluentd-config",then I edit the  ./hack/update-codegen.sh,
![image](https://user-images.githubusercontent.com/27987483/88921563-56707680-d2a1-11ea-8eee-a1e5f3d155c1.png)
Then I ran this "./hack/update-codegen.sh "and I got this error:
![image](https://user-images.githubusercontent.com/27987483/88921689-8750ab80-d2a1-11ea-8846-b05b1a287703.png)
Who can tell me why I got this error after I changed the project name?Many thanks! 

![image](https://user-images.githubusercontent.com/27987483/88921361-f8439380-d2a0-11ea-98d7-1bb4dd91d066.png)

**Comment by Alexbyy** [comment]
when I rename the project into "sample-controller", It can be executed normally。

**Comment by marcus-sa** [comment]
Yeah, I can't seem to get this to work either.

**Comment by wujianqiangwjq** [comment]
Error: Failed making a parser: unable to add directory
