### ISSUE TITLE
how to write controll code

### ISSUE THREAD

**Issue by yyf1986** [kubernetes/code-generator#118]
I use code-generator to generate code (clientset、informers、listers) ,but how to use informers,listers to write myself controll code

**Comment by imkgarg** [comment]
@yyf1986 This link should be helpful: https://engineering.bitnami.com/articles/a-deep-dive-into-kubernetes-controllers.html

**Comment by nikhita** [comment]
@yyf1986 https://github.com/kubernetes/sample-controller has a good end to end example on how to write your own controller using the generated code. :)

Closing.
