### ISSUE TITLE
Empty client generated

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/code-generator#121]
I am generating the client for an API group, and I am getting empty client files.  When I run

```bash
client-gen --go-header-file hack/boilerplate/boilerplate.go.txt --clientset-name versioned --input-base '' --input github.com/cockroachdb/cockroach-operator/api/v1alpha1 --output-package github.com/cockroachdb/cockroach-operator/pkg/client/clientset -v 10
```

I am getting the following errors.

```log
I0309 15:56:55.351826   19978 parse.go:349] importPackage github.com/cockroachdb/cockroach-operator/core/v1alpha1
I0309 15:56:55.351935   19978 parse.go:296] addDir github.com/cockroachdb/cockroach-operator/core/v1alpha1
I0309 15:56:55.352083   19978 parse.go:369] unable to import "github.com/cockroachdb/cockroach-operator/core/v1alpha1": cannot find package "github.com/cockroachdb/cockroach-operator/core/v1alpha1" in any of:
	/tmp/codegen.gopath.9FyC/src/github.com/cockroachdb/cockroach-operator/vendor/github.com/cockroachdb/cockroach-operator/core/v1alpha1 (vendor tree)
	/home/clove/.cache/bazel/_bazel_clove/6daf43ef28bfabb61bbb29fb23d1665c/execroot/com_github_coachroachdb_cockroach_operator/bazel-out/k8-fastbuild/bin/hack/update-codegen.runfiles/com_github_coachroachdb_cockroach_operator/external/go_sdk/src/github.com/cockroachdb/cockroach-operator/core/v1alpha1 (from $GOROOT)
	/tmp/codegen.gopath.9FyC/src/github.com/cockroachdb/cockroach-operator/core/v1alpha1 (from $GOPATH)
```

When I move the API code to a "core" folder, it works.  I am noticing various places in the codebase where the code is returning the value "core" such as in "./cmd/client-gen/types/types.go", but I am not familiar with the codebase enough to figure out how to set the importPackage correctly.  Are we hitting a naming issue with the folder named "api"?  I will provide example code once my PR is stable.  I am working on a custom operator.

**Comment by chrislovecnm** [comment]
Well, I figured it out.  If I renamed the folder to "apis" rather than "api" it works :(

**Comment by michelleN** [comment]
I am running into the same issue but my folder is named apis. I don't know why it doesn't work though.

**Comment by rafi** [comment]
And `xxxx_types.go` won't work, only `types.go`

**Comment by stevekuznetsov** [comment]
@rafi correct! I have a PR (https://github.com/kubernetes/kubernetes/pull/121762) open to relax that - once Tim's back from Kubecon I imagine we'll be able to merge that.
