### ISSUE TITLE
code-gen not generating the files

### ISSUE THREAD

**Issue by onkarbanerjee** [kubernetes/code-generator#123]
Question :- No deepcopy/informer/lister files are created when I run the script `generate-groups.sh`

This is my code directory structure
![image](https://user-images.githubusercontent.com/46961494/113919817-a5dc4e80-9801-11eb-92fe-e045beb63beb.png)

This is my types.go
```
// +genclient

// +genclient:noStatus

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
package v1

type Database struct {
        metav1.TypeMeta   `json:",inline"`
        metav1.ObjectMeta `json:"metadata,omitempty"`

        Spec DatabaseSpec `json:"spec"`
}

// DatabaseSpec is the spec for a Foo resource
type DatabaseSpec struct {
        User     string `json:"user"`
        Password string `json:"password"`
        Encoding string `json:"encoding,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type DatabaseList struct {
        metav1.TypeMeta `json:",inline"`
        metav1.ListMeta `json:"metadata"`

        Items []Database `json:"items"`
}

```

This is my doc.go
```
// +k8s:deepcopy-gen=package
// Package v1 is the v1 version of the API.
// +groupName=example.com
package v1
```

I am running the script like below:
![image](https://user-images.githubusercontent.com/46961494/113920005-d91edd80-9801-11eb-9606-5449c39eabce.png)

But there are no files created ever

**Comment by zq-david-wang** [comment]
append "-v 10" at the end of your command, it should tell where is wrong.

The tool would exit with success code when it has done nothing.......

**Comment by onkarbanerjee** [comment]
@zq-david-wang 

It is not able to find my package it seems, or is the error to do with github credentials?
![image](https://user-images.githubusercontent.com/46961494/114014765-981cdc80-9886-11eb-87c0-051c6824437a.png)
