### ISSUE TITLE
deepcopy --output-package=github.com/examples/pkg/apis, where are generated-codes located

### ISSUE THREAD

**Issue by gy95** [kubernetes/code-generator#126]
i run cmd `deepcopy-gen --go-header-file xxxxx --input-dirs=xxxxxx --output-package=github.com/examples/pkg/apis --output-file-base=zz_generated.deepcopy` to generate codes, 

But i found the code is generated in `./github.com/examples/pkg/apis` , but not in `$GOPATH/github.com/examples/pkg/apis`, how to fix this problem

**Comment by pickfire** [comment]
It figures it out automatically.

Read the help or source code to know this.
```
  -o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/home/xxx/src/go/
```

For me I can't seemed to change the base path.

**Comment by gy95** [comment]
> It figures it out automatically.
> 
> Read the help or source code to know this.
> 
> ```
>   -o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/home/xxx/src/go/
> ```
> 
> For me I can't seemed to change the base path.

Thanks a lot
