### ISSUE TITLE
`groupName` defined in `types.go` is not used for fake clients

### ISSUE THREAD

**Issue by kleimkuhler** [kubernetes/code-generator#135]
When defining multiple APIs with the same version (say `v1`), the `+groupName` tag needs to be in `types.go` instead of `doc.go` in order to not overwrite generated types in `clientset.go`.

However, the group name defined by `+groupName` in `types.go` is not used for the `fake_xxx.go` files.

This results in trying to use test clients that have the incorrect group name and needs to be manually edited.

### Reproduction
I attempted a minimal-ish reproduction with this [go-generator-test](https://github.com/kleimkuhler/go-generate-test).

In this test, `example` and `example2` both use the `v1` version. When `update-codegen.sh`is run, the code generated is mostly correct:
- The correct [SchemeGroupVersion](https://github.com/kleimkuhler/go-generate-test/blob/e0c60d4d0652fb629ed1a0ab06a9471125710e3f/examples/crd/apis/example/v1/register.go#L25) is generated (it's using the `foo.bar` group name)
- `clientset.go` generates the correct package names for both [examples](https://github.com/kleimkuhler/go-generate-test/blob/e0c60d4d0652fb629ed1a0ab06a9471125710e3f/examples/crd/clientset/versioned/clientset.go#L24-L25)

However, if you look at the `fake_xxx.go` files, the group version is [incorrect](https://github.com/kleimkuhler/go-generate-test/blob/e0c60d4d0652fb629ed1a0ab06a9471125710e3f/examples/crd/clientset/versioned/typed/example/v1/fake/fake_clustertesttype.go#L39). It is `example` or `example2` when it _should_ be `foo.bar`.

Now, if `+groupName` is moved from `types.go` to `doc.go` for each of the APIs, then this issue is fixed, but duplicate package names are generated as show [here](https://github.com/kleimkuhler/go-generate-test/blob/a9dd66110e46f4274a32ea24613bee0c7bc760f2/examples/crd/clientset/versioned/clientset.go#L24-L25).

### What the fix should do
I would expect the `+groupName` defined in `types.go` to be used in the generated `fake_xxx.go` files so that the correct group name is used.

**Comment by manusa** [comment]
FWIW the `+groupName` tag should be in a `doc.go` file which is the one that gengo uses to parse the comments.

https://github.com/kubernetes/gengo/blob/2b36238f13e9b8aebe4c286c2ffb2fc71f4be3c5/types/types.go#L121-L126
