### ISSUE TITLE
Provide binary release of code generators

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/code-generator#15]
User story: As a user, I want a simple way to get executables for the code generators at a specific kubernetes release version. 

`go get` gets the code generators at head, but the generators sometimes break backward compatibility.  In order to get the code generators, I need to get the code at a specific release version and then manually build them.  It would be simpler for some contributors if we provided them binary distributions of all of the code generators.

**Comment by munnerz** [comment]
Have you seen the new `generate-groups` and `generate-internal-groups` in the root of this repo, merged in https://github.com/kubernetes/kubernetes/pull/52186?

These take care of compiling the generators for you, and you are able to version against specific versions of the code-generator repository using tags.

The generated code should really be pinned and kept in sync with `kubernetes/apimachinery`, which consequently usually means keeping that also in sync with `kubernetes/client-go` and `kubernetes/api`.

You can see an example of this in use here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-controller/hack/update-codegen.sh
