### ISSUE TITLE
kube::codegen::gen_helpers errors out with 'fatal: Invalid path' error

### ISSUE THREAD

**Issue by HendrikLeier** [kubernetes/code-generator#159]
When I run the following code:

```
source kube_codegen.sh

kube::codegen::gen_helpers \
    --input-pkg-root <repo_name>/pkg/apis \
    --output-base "<base_directory>" \
    --boilerplate "./examples/hack/boilerplate.go.txt"
```

I get the following error:

> fatal: Invalid path '<base_directory>/<repo_name>/pkg/apis/**': No such file or directory

I made sure that the directory exists and contains files that are annotated with `// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object`

I tried crafting the `git grep` by hand. That worked, it might be something in the way of how you call git grep.

I tried varying the path but that didn't do anything.

I am running in a docker container on `golang:1.20.4-buster`
git version is 2.20.1

Am I doing something wrong or is this a bug?

**Comment by oleksii-donoha** [comment]
I believe I've figured it out.
It's all in the paths.
You can use the [sample controller](https://github.com/kubernetes/sample-controller) as an example.

By digging around [this part of the script](https://github.com/kubernetes/code-generator/blob/66e74b777ae2bf43705ec5a0ba97c64ea29349f2/kube_codegen.sh#L114C5-L114C38) you will realize that the path where the codegen will run depends on the parameters you set as `--input-pkg-root, --output-base`. 

Long story short:
1. Assuming you cloned into the home directory, your directory structure should be like this: `${HOME}/${GO_PACKAGE_NAME}`. So if your package is `github.com/foo/bar`, then the path should be `/home/${USER}/github.com/foo/bar`
2. The original script assumes that the package name has 2 parts divided by `/`, i.e. `k8s.io/sample-controller`. If your package (most likely) is called `github.com/foo/bar`, then the package name has 3 parts. This means you need to add one more `..` to your output base: `--output-base "$(dirname "${BASH_SOURCE[0]}")/../../.."` -> `"$(dirname "${BASH_SOURCE[0]}")/../../../.."`

You can of course completely override the out base, but the path should still contain the github path.

**Comment by thockin** [comment]
Most of the path weirdness is now fixed.

/close
