### ISSUE TITLE
--with-applyconfig creates import loop for some groupName values

### ISSUE THREAD

**Issue by npinaeva** [kubernetes/code-generator#168]
Using sample-controller as a reproducer, add `--with-apply-config` to https://github.com/kubernetes/sample-controller/blob/f53405abe7423d4addcbf2c4495604f02d6ef85f/hack/update-codegen.sh#L32-L36
Then changing groupName, for example to `samplecontroller2.k8s.io`, and running update-codegen will result in the following import from `pkg/generated/applyconfiguration/samplecontroller/v1alpha1/foo.go`
```
import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	v1alpha1 "k8s.io/sample-controller/pkg/generated/applyconfiguration/samplecontroller/v1alpha1"
)
```
where the last line imports the same package it is a part of. Using `--apply-config` without group name change works fine.

Similar examples in the repo use simple structs like https://github.com/kubernetes/code-generator/blob/75dbfb954ff33ef26dc084b28f63d1ac478fc0f6/examples/HyphenGroup/apis/example/v1/types.go#L45-L47 that don't create applyconfiguration files and are imported directly from e.g. `k8s.io/code-generator/examples/HyphenGroup/apis/example/v1`

So what is the expected behaviour here? Am I missing some tricky flags maybe?

**Comment by erikgb** [comment]
I observe the same symptom (import cycle) when trying to upgrade `applyconfiguration-gen` from v0.29.3 to v.0.30.0 in https://github.com/statnett/image-scanner-operator/pull/908. But my use case is generating applyconfigurations from another project (https://github.com/kubernetes-sigs/wg-policy-prototypes in this case).

This used to work up till now. Has this use case never been supported? Or did I do something wrong when migrating the CLI args?

I also found https://github.com/kubernetes/kubernetes/pull/124193, which seems related.

Sorry to bother you, but I would love to get some input from @thockin and/or @jpbetz.

**Comment by thockin** [comment]
I *think* that this is solved by https://github.com/kubernetes/kubernetes/pull/124371 which merged last week and should be in 1.30.1

**Comment by erikgb** [comment]
Thanks Tim! I should have tested with the master branch. Sorry! 🙈 I have verified my issue is resolved with https://github.com/kubernetes/code-generator/commit/ff061d68bdb94dcf0f35733dd2b5821ce4da1374

**Comment by thockin** [comment]
@npinaeva are you cool with closing this issue, then?

**Comment by npinaeva** [comment]
Works fine now!
