### ISSUE TITLE
applyconfiguration-gen generates an import cycle

### ISSUE THREAD

**Issue by Gchbg** [kubernetes/code-generator#171]
Hi,

When I run the current (0.30.0) verison of code-generator, I see that applyconfiguration-gen generates an import cycle (a package importing itself). It works fine on 0.29.4.

This happens on my kubebuilder-generated project that uses the v4 layout. I noticed that if I move my types to be under a directory other than the default `api/`, the generator does not generate an import cycle. So this might be related to #167.

You can find a minimal reproducer here: https://github.com/Gchbg/myproject 

Just run
```
./gen.sh
go run .
```

```
package github.com/gchbg/myproject
	imports github.com/gchbg/myproject/client/applyconfiguration/api/v1alpha1
	imports github.com/gchbg/myproject/client/applyconfiguration/api/v1alpha1: import cycle not allowed
```

Is there a workaround I can use that allows me to keep the `api/` directory?

Thanks!

**Comment by Wangyiwei-So** [comment]
I also encountered the same problem. 
```
CODEGEN_PKG="vendor/k8s.io/code-generator/"
source "${CODEGEN_PKG}/kube_codegen.sh"
kube::codegen::gen_client \
  --output-dir apis/client-go \
  --output-pkg tq-gitlab.zhejianglab.com/infrahi/odre/apis/client-go \
  --boilerplate hack/codegen/boilerplate.go.txt \
  --with-watch \
  --with-applyconfig \
  apis
```
```
❯ tree ./apis
./apis
├── meta
│   └── v1
│       ├── auth_types.go
│       ├── basic_type.go
│       ├── cluster_types.go
│       ├── doc.go
│       ├── register.go
```
after gen
the applyconfigration file will be
```
metav1 "tq-gitlab.zhejianglab.com/infrahi/odre/apis/client-go/applyconfiguration/meta/v1"
import cycle not allowed
```
