### ISSUE TITLE
generate-groups.sh doesn't like API groups that use `.` in the name

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/code-generator#19]
Two things, actually:
- If I name a group `thing.k8s.io`, `generate-groups.sh` requires that the version directories be in a directory named `thing.k8s.io`.
- If you comply, then `generate-groups.sh` will try to import e.g. the `v1alpha1` package as `thing.k8s.iov1alpha1 "..."`, which is not a valid go import. gofmt then fails on the `.`s and everything explodes.

**Comment by lavalamp** [comment]
cc @caesarxuchao @mbohlool

**Comment by munnerz** [comment]
I'm not seeing this behaviour - have you got some example code to help demonstrate?

My doc.go specifies a group name containing multiple `.`: https://github.com/jetstack/navigator/blob/master/pkg/apis/navigator/v1alpha1/doc.go

**Comment by mtaufen** [comment]
Ah, sorry, I should have clarified; this happens if you make the directory name match the group name, and the name includes dots; e.g. `pkg/apis/thing.k8s.io`.

For now, it seems everyone gets around this by avoiding dots in the dir names.
