### ISSUE TITLE
Imports lowercased

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/code-generator#20]
Several packages are lowercased during package generation. This causes import errors if, for instance, your Github account uses uppercase characters.

Some packages are also generated under lowercased paths so these packages are generated under a different directory than your project. For example my project might be in $GOPATH/src/github.com/IanLewis/myapp and code-generator will generate some files under $GOPATH/src/github.com/ianlewis/myapp

**Comment by AkihiroSuda** [comment]
This is critical for me, any update?

**Comment by wstrange** [comment]
Is there any workaround for this?

**Comment by n3wscott** [comment]
The issue comes from here: https://github.com/kubernetes/code-generator/blame/c7a364cb8cf12ce4704f017c0a403c55db3e752b/cmd/client-gen/generators/generator_for_clientset.go#L63

I am looking into a fix.

**Comment by n3wscott** [comment]
Also here: https://github.com/kubernetes/code-generator/blob/master/cmd/client-gen/generators/scheme/generator_for_scheme.go#L72

**Comment by erutherford** [comment]
This is definitely still an issue could someone please remove the rotten flag from this?

**Comment by ianlewis** [comment]
Not sure it will work for me but..
/remove-lifecycle rotten
/remove-lifecycle stale
