### ISSUE TITLE
Generator only works if k8s.io/apimachinery is in the $GOPATH

### ISSUE THREAD

**Issue by markmandel** [kubernetes/code-generator#21]
Whenever I attempt to run `update-codegen.sh` , but constantly get the below stacktrace.

```
Generating deepcopy funcs
F1104 02:57:44.419529      35 main.go:79] Error: Failed executing generator: some packages had errors:
type "k8s.io/apimachinery/pkg/runtime.Object" in k8s:deepcopy-gen:interfaces tag of type k8s.io/apimachinery/pkg/runtime.Object is not an interface, but: ""
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc420136b00, 0xc42012b080, 0x104, 0x15a)
        /go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x83eb60, 0xc400000003, 0xc4200cf1e0, 0x81ea9f, 0x7, 0x4f, 0x0)
        /go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x83eb60, 0x3, 0x6ebfc7, 0x9, 0xc4200e7f48, 0x1, 0x1)
        /go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6ebfc7, 0x9, 0xc4200e7f48, 0x1, 0x1)
        /go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        /go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:79 +0x253
```

I created a simple test case using a Dockerfile below, using the sample-controller example, which replicates the problem.

```docker
FROM golang:1.9.2

ENV PATH=$PATH:/go/bin
RUN go get -u k8s.io/code-generator/...
RUN go get -d github.com/kubernetes/sample-controller
RUN mkdir -p /go/src/k8s.io/kubernetes/hack/boilerplate && touch /go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt
WORKDIR /
RUN CODEGEN_PKG=/go/src/k8s.io/code-generator /go/src/github.com/kubernetes/sample-controller/hack/update-codegen.sh
```

Help?

**Comment by markmandel** [comment]
I worked out the issue - this doesn't work unless k8s.io/apimachinery is in the GOPATH, if it is just vendored, then deepcopy can't find it. At the very least, this needs to be documented somewhere.

**Comment by jinghzhu** [comment]
+1 for fix or documentation.

I encounter the same issue and only find the solution mentioned before by Google.

**Comment by sttts** [comment]
@markmandel @jinghzhu do you have a small example repo where this can be seen?

**Comment by markmandel** [comment]
@sttts you can copy the above section into a `Dockerfile` and do a `docker build .` and see the failure in action :smile:

**Comment by sttts** [comment]
The cause for the issue described above is that the generators are not called from the sample-apiserver directory. Only then gengo (the Golang parsing library below) can pick up the vendor/ directory properly. The following Dockerfile passes the deepcopy-gen call, but fails at client-gen (compare https://github.com/kubernetes/kubernetes/pull/57143 for a fix).

```
FROM golang:1.9.2

ENV PATH=$PATH:/go/bin
ENV GOPATH=/go
RUN go get -u k8s.io/code-generator/...
RUN go get -d k8s.io/sample-controller
RUN ls -l /go/src/k8s.io
RUN mkdir -p /go/src/k8s.io/kubernetes/hack/boilerplate && touch /go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt
WORKDIR /go/src/k8s.io/sample-controller
RUN CODEGEN_PKG=../../k8s.io/code-generator bash -xe hack/update-codegen.sh
```

**Comment by sttts** [comment]
PR welcome to improve our codegen shell scripts to cope with out-of-dir invocations.

**Comment by sttts** [comment]
Also not that the package is called `k8s.io/sample-controller`, not `github.com/kubernetes/sample-controller`.

**Comment by rahulkrishnanfs** [comment]
I am facing the same issue

**Comment by sttts** [comment]
@rahulkrishnanfs compare my comment https://github.com/kubernetes/code-generator/issues/21#issuecomment-351368398. You have to call the generator script with a relative CODEGEN_PKG. Does it help?

**Comment by mattysweeps** [comment]
/reopen

See https://github.com/kubernetes/kubernetes/issues/79149#issuecomment-966482552
Code generator users are still running into this issue.

Either the documentation should inform users to prepare their GOPATHS with the necessary dependencies or the code-generator be improved so it no longer has this requirement.

**Comment by mattysweeps** [comment]
@markmandel please consider reopening this issue. I see no evidence that it has been solved, and [users are still running into issues](https://github.com/kubernetes/kubernetes/issues/79149#issuecomment-966482552). Thank you.
