### ISSUE TITLE
Autogenerate register.go files

### ISSUE THREAD

**Issue by markmandel** [kubernetes/code-generator#24]
Looking at register.go - it looks like these could be generated via this tool as well.

When implementing a CRD it's not very clear what to put in these files, and a simple copy paste from the `sample-controller` with minor edits works, but it seems like this could be easily solved via code generation, which would also solve the documentation issue.

Extra context:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1511820482000365

Friction log:
https://docs.google.com/a/google.com/document/d/1N1pBov7Odpg_u-kILHcswYh4VO-aMlYQdFIH64DYeek/edit?disco=AAAABhkn5r4

**Comment by sttts** [comment]
This could be something for kube-gen https://github.com/kubernetes/community/pull/1315.

**Comment by nikhita** [comment]
Same issue reported in k/k: https://github.com/kubernetes/kubernetes/issues/65612. Closing this in favour of it.

/close
