### ISSUE TITLE
type net.IP has no field or method DeepCopy

### ISSUE THREAD

**Issue by xh3b4sd** [kubernetes/code-generator#25]
When generating clients for types that refer to `net.IP` the code generator generates invalid go code which is not able to compile. See for instance https://github.com/giantswarm/apiextensions/pull/16. I am wondering how this is supposed to work. Can somebody elaborate on this? Our workaround was to rather use type `string` than `net.IP` but I feel like this should be fixed upstream. Cheers.

**Comment by tanner-bruce** [comment]
I believe I am seeing the same behaviour when trying to use a struct inside my CRD spec that comes from another package
