### ISSUE TITLE
Generate json-schema from go types

### ISSUE THREAD

**Issue by erictune** [kubernetes/code-generator#28]
When you create a CRD, it can have a schema defined using json-schema.

In github.com/kubernetes/sample-controller the client libraries for a controller are generated from a go API definition, and CRDs are created, but there is no schema for the CRD, which means less validation.

It would be nice to generate the json-schema for the CRD from the Go types.  So, this is proposing a new generator that generates json-schema for CRDs from go types.

**Comment by erictune** [comment]
xref https://github.com/kubernetes/sample-controller/issues/2

**Comment by sttts** [comment]
@erictune we discussed the very same idea at KubeCon. We have openapi-gen which produces a Golang snippet now which is very similar to a JSON Schema already. @munnerz wanted to prototype a change to openapi-gen with your described goal.

**Comment by munnerz** [comment]
Yep - likely I won't have a chance to get onto this until next week, as this is my final week before xmas. I think @sttts and I discussed initially adding an 'output format' parameter to openapi-gen in order to facilitate this.

**Comment by perotinus** [comment]
+1 to this. I'm looking into having the cluster registry be a CRD and this would be a boon for that.

**Comment by sttts** [comment]
https://github.com/kubernetes/kube-openapi/pull/37 needs review time.

**Comment by munnerz** [comment]
I’m happy to follow up with additional features (such as comments tags to
allow specifying regex’s to validate with, etc) once the structure/design
is accepted too.

I just didn’t want to rush ahead and introduce a load of new functionality
without being sure that the way it’s implemented makes sense!

**Comment by erictune** [comment]
I just came across this which looks similar:
https://github.com/ant31/crd-validation

**Comment by lavalamp** [comment]
I expect we will take this on in kube-openapi and not here.

**Comment by sttts** [comment]
Work on this is going on in http://github.com/kubernetes-sigs/controller-tools.

**Comment by thockin** [comment]
/close 

stale?
