### ISSUE TITLE
Place DeepCopy Funcs in Separate package than types

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/code-generator#31]
As the actual types are in the same package as the generated DeepCopy funcs, the GoDoc has a lot of extra noise in it.

**Comment by nikhita** [comment]
> As the actual types are in the same package as the generated DeepCopy funcs

I think this is true for _all_ types now (even built-in) and changing it would have a bigger cost than fixing godoc.

@sttts opinions?

**Comment by sttts** [comment]
This won't be changed any time soon. Is there no way to opt-out of doc generation for a method?

**Comment by sttts** [comment]
As this won't happen because
- it breaks all existing code using deepcopy
- it leads to ugly func names
- and it makes `DeepCopyObject` like interface implementation impossible
let's close this issue.
