### ISSUE TITLE
Support code generation for repositories that use both CRD and EAS

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/code-generator#36]
I have a repo, where we only had CRDs. So, I used the generate-groups.sh script.
Now, we have added an EAS in the same repo.
Now, I have to use generate-internal-groups.sh for all types
because I want to have a single client package.
So, I am forced to add internal types even for CRDs now.

It will be good not to have to have internal types for CRDs.

cc; @sttts

**Comment by sttts** [comment]
As discussed on slack, IMO the right approach is to create a versioned client (via generate-groups.sh) for both EAS+CRD types to get one clientset. Then for deepcopy,conversion,defaulter call the generator-internal-groups.sh script against the EAS resources.

**Comment by tamalsaha** [comment]
Based on @sttts ' suggestion I have done this https://github.com/appscode/searchlight/blob/master/hack/codegen.sh

- First generate "deepcopy,defaulter,conversion" using generate-internal-groups.sh for EAS types.
- Then generate all using generate-groups.sh for all types (CRD + EAS)
