### ISSUE TITLE
generate-groups.sh not creating lister and informer

### ISSUE THREAD

**Issue by trstringer** [kubernetes/code-generator#38]
When I invoke `generate-groups.sh` by specifying all generators, informers and listers are not created in my package. Logging doesn't give any indication of failures. Below is a repro for me.

Is there something I'm doing wrong in my workflow to generate and scaffold out the code for a custom resource controller?

```
$ GITHUB_USERNAME=trstringer
$ cd $GOPATH/src/github.com/$GITHUB_USERNAME
$ mkdir testcontroller
$ cd testcontroller
$ mkdir -p $GOPATH/src/github.com/$GITHUB_USERNAME/testcontroller/pkg/apis/testresource/v1
$ echo "package v1" >> $GOPATH/src/github.com/$GITHUB_USERNAME/testcontroller/pkg/apis/testresource/v1/root.go
$ go get k8s.io/code-generator/...
$ cd $GOPATH/src/k8s.io/code-generator
$ ./generate-groups.sh all github.com/$GITHUB_USERNAME/testcontroller/pkg/client github.com/$GITHUB_USERNAME/testcontroller/pkg/apis testresource:v1
Generating deepcopy funcs
Generating clientset for testresource:v1 at github.com/trstringer/testcontroller/pkg/client/clientset                                                           
Generating listers for testresource:v1 at github.com/trstringer/testcontroller/pkg/client/listers                                                                                       
Generating informers for testresource:v1 at github.com/trstringer/testcontroller/pkg/client/informers    
$ cd $GOPATH/src/github.com/$GITHUB_USERNAME/testcontroller
$ tree
.
└── pkg
    ├── apis
    │   └── testresource
    │       └── v1
    │           └── root.go
    └── client
        └── clientset
            └── versioned
                ├── clientset.go
                ├── doc.go
                ├── fake
                │   ├── clientset_generated.go
                │   ├── doc.go
                │   └── register.go
                ├── scheme
                │   ├── doc.go
                │   └── register.go
                └── typed
                    └── testresource
                        └── v1
                            ├── doc.go
                            ├── fake
                            │   ├── doc.go
                            │   └── fake_testresource_client.go
                            ├── generated_expansion.go
                            └── testresource_client.go

13 directories, 13 files
```

It's also worth mentioning that after the above repro, I modified the `generate-groups.sh` bash script and I added `set -x` at the top. I took the `informer-gen` and `lister-gen` commands and ran them manually. They both had zero return codes showing success, but the code was still not placed in the target package.

// cc @ritazh

**Comment by sttts** [comment]
https://github.com/trstringer/testcontroller – 404.

**Comment by trstringer** [comment]
I figured it out. I was missing the necessary tags in my API package.

**Comment by BassinD** [comment]
Hi, I have the same problem. Could you share the solution?

**Comment by wubo0067** [comment]
> I figured it out. I was missing the necessary tags in my API package.
I also meet this problem, please ask me which important tags, thank you very much

**Comment by wubo0067** [comment]
@trstringer ，I also meet this problem, please ask me which important tags, thank you very much！

**Comment by dylanhitt** [comment]
For those that may still be having trouble in the future @trstringer  has a great [blog](https://trstringer.com/extending-k8s-custom-controllers/) about using the generator. Pay attention in the files where `// +<tag_name>[=value]` is present. Exact reference can be scene both in the blog post and [here in the sample-controller](https://github.com/kubernetes/sample-controller/blob/a1a67935a65841952d990076df30b6649f25bf53/pkg/apis/samplecontroller/v1alpha1/types.go#L24).

**Comment by onkarbanerjee** [comment]
But it still doesn't work right? I have followed all the instructions to the tee in https://trstringer.com/extending-k8s-custom-controllers/ but listers and informers are never there

**Comment by shubham-cmyk** [comment]
Using the same comment as give on the https://trstringer.com/extending-k8s-custom-controllers/
The problem was occuring due the fact that the name of  dir specified under the pkg/api wasn't same as the GroupName
