### ISSUE TITLE
Inconsistency of generated informers and the rest when CRD names ends in "s" and if CRD name has capital letters within the word

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes/code-generator#39]
For example:
if crd kind singualr is kinesis  ->> the generated code for informers becomes kinesises , it automatically try to "correct" the word by adding an "e", but they keep kinesiss for the rest of the generated code. The crd requires plural is just adding a s to singular in order to properly create it in the k8s master.  So I cannot fix one without failing the other.

Another example: 
If my crd is called dyanmodbtable but in pkg/api/xxx/v1alpha../types.go.
the struct I called it DynamoDbTable, again generated informers will use “DynamodbTableList” to register informers and listers. Note that is gets put "D"bTable as "d"btable. 
error message when starting controller:
*v1alpha1.DynamoDbTable: no kind “DynamodbTableList” is registered for version 

Steps to invooke code-generater
client-gen:
	rm -rf vendor/k8s.io/code-generator
	git clone https://github.com/kubernetes/code-generator  vendor/k8s.io/code-generator
	cd vendor/k8s.io/code-generator && git checkout tags**/kubernetes-1.9.0**
	./code-gen/update-codegen.sh

Why are we autocorrect types all the time? If so, can we make it consistent so that when create the crd on k8s, it errors out?   Or better yet, fails the code-generation if the naming fails some rules. IT is not obvious and hard to debug.

**Comment by tamalsaha** [comment]
Try with the 1.10 release. There were some fixes done in this pluralization logic.
