### ISSUE TITLE
deepcopy-gen does not work with circular references

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/code-generator#40]
I am trying to generate deepcopy where two types depend on each other. `DeepCopyInto` method is not generated for the alias type.

Here is an example repo that shows the bug: https://github.com/tamalsaha/kube-deepcopy-bug
Types: https://github.com/tamalsaha/kube-deepcopy-bug/blob/master/apis/demo/v1alpha1/types.go

cc: @sttts

**Comment by sttts** [comment]
Compare with https://github.com/kubernetes/gengo/blob/master/examples/deepcopy-gen/output_tests/aliases/doc.go. Aliases of slices should work.

**Comment by tamalsaha** [comment]
I was using code-generator from 1.9 release. That was causing problem. I switched to code-generator from 1.10 release. That seems to be working fine. Thanks @sttts .
