### ISSUE TITLE
Why not generate defaulters in generate-groups.sh?

### ISSUE THREAD

**Issue by grantr** [kubernetes/code-generator#46]
I'm writing a CRD that uses defaulters. The documentation for generate-groups.sh states that it can generate defaulters (`the generators comma separated to run (deepcopy,defaulter,client,lister,informer) or "all".`) but it doesn't actually.

Is this intentional? Defaulters do get generated for internal types, but I haven't seen a clear definition of internal versus external so I don't know what types should be internal, or why defaulters (and conversions) only apply to internal types.

**Comment by whypro** [comment]
I have the same question. Is this a mistake?

**Comment by sttts** [comment]
Defaulters are only used in aggregated API servers. Those use internal versions. For CRDs (and hence `generator-groups.sh` defaulters don't work. If you want defaults, look at the "OpenAPI default" feature in 1.15 (still alpha, will be beta in 1.16).
