### ISSUE TITLE
How to use go-to-protobuf

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/code-generator#5]
I would like to generate proto files for my kubernetes CRDs using go-to-protobuf. I tried to look int to the main Kubernetes repo and could not figure out how to do that. Can you give me some pointers on how to generate protobuf file from the hand written GO CRD types.

Any help is greatly appreciated!

**Comment by frankgreco** [comment]
I am also very interested in this. 

1) How can we autogenerate `generated.proto`
2) If we do provide protobuf declarations, will they automatically be used by the apiextentions server?

**Comment by frankgreco** [comment]
I believe the code to so is [https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf](https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf) so i'm going to try to sift through and figure out how to use that.

**Comment by tamalsaha** [comment]
I have been told that protobufs can't be used with CRDs. So, it is not useful or usable for Kubernetes extensions developers.

**Comment by frankgreco** [comment]
Who told you that??

**Comment by tamalsaha** [comment]
From Slack:

![no-proto](https://user-images.githubusercontent.com/94814/31699727-65936a2c-b379-11e7-97f8-38bf4481fbfb.png)
