### ISSUE TITLE
go modules support

### ISSUE THREAD

**Issue by tcolgate** [kubernetes/code-generator#57]
The generators insist on putting generated code into the GOPATH, rather than relative to the local directory the tool is running in.

For the simplest use case of generating code for a single controller, it seems like it should be possible to support building/generating outsisde of a GOPATH, using go modules. It's not clear to me what other use cases this tool supports, and/or if using it outside of GOPATH makes sense (hopefully it can, as I think GOPATH's long term support is in question)

**Comment by nikhita** [comment]
Go modules support is now in.

/close

**Comment by christopherhein** [comment]
@nikhita is there a specific way to use this with gomodules… noticed sample-controller doesn't work out of the box with it… see https://github.com/kubernetes/sample-controller/issues/47

**Comment by parhamdoustdar** [comment]
Hi @nikhita, are there any instructions for using the code-generator package when installed as a module?

Right now, i've done `go get -m k8s.io/code-generator`, but I'm not sure how to proceed.

**Comment by sttts** [comment]
Compare https://github.com/kubernetes/sample-apiserver#when-using-go-111-modules. `go mod vendor` downloads what you need.

**Comment by parhamdoustdar** [comment]
Thanks a lot for referring me to that page, I figured what I was doing wrong. I needed to create a `tools.go` file which would import the `k8s.io/code-generator` package, so that it would end up in my `vendor` directory when I did `go mod vendor`.

Thanks for the help!

**Comment by mkmik** [comment]
@parhamdoustdar I tried but it doesn't vendor the `hack` directory (because they don't contain .go files?)

```
F0716 10:59:28.908622   89340 deepcopy.go:131] Failed loading boilerplate: open /Users/mkm/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
```

```
$ ls -d vendor/k8s.io/code-generator
vendor/k8s.io/code-generator
$ ls -d vendor/k8s.io/code-generator/hack
ls: cannot access 'vendor/k8s.io/code-generator/hack': No such file or directory
```

any idea how to trick `go mod vendor` to also include that dir?

**Comment by mkmik** [comment]
hmm, apparently even if I make that dir available in the vendor dir, the scripts will try to use the one in the GOPATH

**Comment by parhamdoustdar** [comment]
I also don't have the `vendor/k8s.io/code-generator/hack` directory. However, I copied the `update-codegen.sh` and `verify-codegen.sh` into my project's `hack` directory. You can see the directory [here](https://github.com/bookingcom/shipper/tree/master/hack).

**Comment by sttts** [comment]
Those scripts in the hack dir are not for consumers, but developers of k8s.io/code-generator. You only need those at the root package.

**Comment by mkmik** [comment]
then I guess I'm calling `generate-groups.sh` wrong because it fails if those files can't be found.

In all fairness, I have no idea what I'm doing, I inherited a project that was calling:

```
//go:generate ../../../../vendor/k8s.io/code-generator/generate-groups.sh all github.com/bitnami-labs/sealed-secrets/pkg/client github.com/bitnami-labs/sealed-secrets/pkg/apis sealed-secrets:v1alpha1
```

and it fails with `F0716 10:59:28.908622   89340 deepcopy.go:131] Failed loading boilerplate: open /Users/mkm/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory`

@sttts should I do something differently?

**Comment by sttts** [comment]
@mkmik pass your own boilerplate with `--go-header-file "some/other/boilerplate.go.txt`

**Comment by sttts** [comment]
Compare https://github.com/kubernetes/sample-controller/blob/master/hack/update-codegen.sh#L32

**Comment by mkmik** [comment]
@stts thanks! I didn't realize that template was the responsibility of the user; it seems obvious in retrospect.

would it make sense to just make the `--go-header-file` flag mandatory so people don't fall in the trap of ignoring this step (which accidentally works if the code-generator dep is present in the GOPATH)?

**Comment by nikhita** [comment]
> which accidentally works if the code-generator dep is present in the GOPATH

We intentionally default it that way, so that people won't have to use the `--go-header-file` unless necessary. :grimacing: 

> would it make sense to just make the --go-header-file flag mandatory so people don't fall in the trap of ignoring this step

Instead of making this mandatory, I think we could improve the error message and documentation around this. As a side-note, we intend to make code-generation more module-friendly, so this problem should go away then - https://github.com/kubernetes/publishing-bot/pull/196#issuecomment-511653822.

**Comment by mkmik** [comment]
@nikhita, thanks; yeah using module aware functions to locate the default file would do the trick.

**Comment by marccarre** [comment]
@nikhita, @sttts, what is the recommended way to vendor `code-generator` via Go modules to also pull non-Go files, e.g. `generate-groups.sh`? (Apologies if already documented elsewhere, I couldn't find this.)

**Comment by alexellis** [comment]
@marccarre I noticed that you haven't had an answer on this. What did you settle on?

**Comment by marccarre** [comment]
@alexellis, sorry, this was almost two years ago and I'm afraid I can no longer remember. 😔
(Especially as I moved on to something else in the meantime.)
