### ISSUE TITLE
Why informer-gen need genclient:nonNamespaced annotated by SecondClosestCommentLines

### ISSUE THREAD

**Issue by luguoxiang** [kubernetes/code-generator#59]
I created a custom resource named Installation and add following annotation so that code-generator can generate code for me. The annotation works for deepcopy-gen and client-gen, but it seems informer-gen can not recognize  "genclient:nonNamespaced".
```
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +genclient
// +genclient:nonNamespaced
type Installation struct {
```
After reading the code informer-gen/generaters/versioninterfaces.go , It seems the annotation must be written like following(SecondClosestCommentLines):
```
// +genclient:nonNamespaced

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +genclient
```
Why informer-gen need the annotation written like this?

**Comment by nikhita** [comment]
@sttts I think you fixed something similar to this?

**Comment by sttts** [comment]
@nikhita in gengo, but not in general if I remember right.

**Comment by sttts** [comment]
PR very welcome

**Comment by nikhita** [comment]
I can take a look at this, but not assigning myself since I've got some stuff on my plate already. Will get back to this in a few days, if no one has already solved it.

**Comment by Kyrremann** [comment]
Has anyone checked more into this?
