### ISSUE TITLE
In conversion gen if the pkg is wrong it results in nil pointer error

### ISSUE THREAD

**Issue by maleck13** [kubernetes/code-generator#7]
When using the conversion-gen tool recently, I had accidentally misspelled the package name in the comments for conversion-gen. When I ran the conversion-gen tool it gave me an error.

The command I ran was:
```
 conversion-gen --input-dirs github.com/maleck13/kubeop-bot/pkg/apis/kubeopbot/v1alpha1 --input-dirs github.com/maleck13/kubeop-bot/pkg/apis/kubeopbot -o ${HOME}/projects/src --go-header-file ./artifacts/boilerplate/boilerplate.go.txt -O zz_generated.conversion 
```

The error was

```k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x124f4e0]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators.getManualConversionFunctions(0xc4267f9440, 0x0, 0xc42683de60)
	/Users/kelly/work/go/src/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators/conversion.go:143 +0x1a0
k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators.Packages(0xc4267f9440, 0xc4200a4480, 0x12ec128, 0x6, 0xc4267f9440)
	/Users/kelly/work/go/src/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/generators/conversion.go:286 +0xc4b
k8s.io/kubernetes/vendor/k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc4200a4480, 0xc42001cdb0, 0x12ec128, 0x6, 0x12faed0, 0x12fa90b, 0x5f)
	/Users/kelly/work/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/args/args.go:165 +0x1e6
main.main()
	/Users/kelly/work/go/src/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen/main.go:76 +0x28c

```

It took quite some time to track down that the issue was I had misspelled as shown below in the package in the comment:
```
// +k8s:conversion-gen=github.com/maleck13/kubeop-bot/pkg/apis/kubopbot
```

I tracked down the issue to the following line of code:
https://github.com/kubernetes/code-generator/blob/master/cmd/conversion-gen/generators/conversion.go#L294

Changing this to the following:
```
	p := context.Universe[pp]
			if p == nil {
				glog.Errorf("package %s was not found", pp)
				continue
			}
```

Made it much clearer what was happening. I am happy to create a PR with this change back against the main kubernetes repo, but wasn't sure if perhaps in this case it should exit instead of just log the error?

**Comment by spxtr** [comment]
> wasn't sure if perhaps in this case it should exit instead of just log the error?

Just exit, since the output will probably wrong if you continue.

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/53567.

Closing.
/close
