### ISSUE TITLE
Cannot run generate scripts - generate-groups.sh: permission denied

### ISSUE THREAD

**Issue by nimrodshn** [kubernetes/code-generator#72]
Following the steps detailed here: https://github.com/kubernetes/sample-apiserver/#when-using-go-111-modules, I am receiving an `../../vendor/k8s.io/code-generator/generate-groups.sh: permission denied`  error attempting to run `go generate` on the following - 
```
//go:generate ../../vendor/k8s.io/code-generator/generate-groups.sh all gitlab.cee.redhat.com/service/uhc-clusters-service/pkg/hive github.com/openshift/hive/pkg/apis "hive:v1alpha1"
```
I have ran `go mod vendor` and included `k8s.io/code-generator` in my code base:
```
import _ "k8s.io/code-generator"
```

Does anyone know whats wrong with the steps I am taking?
cc: @sttts @nikhita

**Comment by nikhita** [comment]
`go mod vendor` does not set scripts as executable which leads to the `permission denied` error. See https://github.com/kubernetes/kubernetes/pull/79081 for more details.

If you directly use the `hack/update-codegen.sh` scripts, it'll work correctly. :)
If you invoke `go generate` yourself, you'll have to set the `generate-groups.sh` with executable permissions.

**Comment by nimrodshn** [comment]
@nikhita How does one use `hack/update-codegen.sh`? is there a documentation to using it?

**Comment by nikhita** [comment]
> How does one use hack/update-codegen.sh?

@nimrodshn using the script https://github.com/kubernetes/sample-apiserver/blob/master/hack/update-codegen.sh :)

> is there a documentation to using it?

The script will automatically generate code if you change any of the types. More info about that here: https://github.com/kubernetes/sample-apiserver/#changes-to-the-types, https://github.com/kubernetes/code-generator/#resources

**Comment by nimrodshn** [comment]
Thanks @nikhita !

**Comment by nimrodshn** [comment]
@nikhita Now I am getting: 
```
build ...: cannot load k8s.io/code-generator: no Go source files
```
When I am trying to `make build` my project - How do I fix this?
I would really like to avoid copying the `update-codegen.sh` file to my project or bringing other projects to my `GOPATH` - ideally all the dependencies should be vendored.

**Comment by dvaldivia** [comment]
@nikhita I'm getting problems during build on an gitflow, even with `go mod vendor` i get 

```
....
go: finding k8s.io/apimachinery v0.17.3
build k8s.io/code-generator: cannot load k8s.io/code-generator: no Go source files
##[error]Process completed with exit code 1.
```

**Comment by dvaldivia** [comment]
@nimrodshn did you fixed this?

**Comment by bentito** [comment]
Same as @dvaldivia , I don't understand how to properly cause the bash script, `generate-groups.sh` to be available in a `go mod` build?
