### ISSUE TITLE
Code generator does not generate clients when group information isn't presnt in the directory path

### ISSUE THREAD

**Issue by joshiomkarj** [kubernetes/code-generator#76]
While using another generator (like kubebuilder) and code-generator together, I observed that the client, listers and informers are not generated. Upon more investigation, it seems that while running generate-groups.sh script, when the group is provided, it must exist in the directory structure. 

When the apis are created with kubebuilder, the directory structure is _./api/<version>/*_types.go_ with group information aggregated in a separate file. For example, for group cr, version v1beta1 and file object_types.go, the directory structure required by codegen would be _./api/cr/v1beta1/object_types.go_ however the one generated by kubebuilder is _./api/v1beta1/object_types.go_. 

While this has been issue raised on kubebuilder [kubebuilder-739](https://github.com/kubernetes-sigs/kubebuilder/issues/739), what is unclear is why code-generator enforces group in the path when path to actual types is provided while running the script.

Could someone help me understand whether this is a bug that can be addressed or does the code-generator has some inherent dependency on the group being a part of the path itself?

**Comment by cliveseldon** [comment]
Any update on this or workaround as I also would like to use clientgen to build a clientset from a kubebuilder bsaed project.
