### ISSUE TITLE
Unable to generate informer code with a package that has a dot in kubernetes-1.16.0-beta.2

### ISSUE THREAD

**Issue by FxKu** [kubernetes/code-generator#77]
We are using the code-generator in our [project](https://github.com/zalando/postgres-operator) for about a year now. Currently, I'm trying to switch the build process from glide to go modules but I'm struggling to update the code generation. One of our packages is called `acid.zalan.do` which doesn't seem like a valid format. Can I use some argument to choose some other name on-the-fly?

In the [master](https://github.com/zalando/postgres-operator/blob/master/pkg/generated/informers/externalversions/acid.zalan.do/interface.go) the package is only called `acid`. Don't know how it got there. Now `informer-gen` always produces `acid.zalan.do`, although its written without dots in the [register.go](https://github.com/zalando/postgres-operator/blob/master/pkg/apis/acid.zalan.do/register.go) file.

Thanks in advance for any help!

**Comment by FxKu** [comment]
Just noticed that it's probably duplicate to #19

**Comment by FxKu** [comment]
Ok, we found out what caused this breaking change! It's this commit: https://github.com/kubernetes/code-generator/commit/5ac21ed6de7ac91d03e7917872c463de906d46a6

Before the first part of our package was taken, which is `acid`. As in the other PR, I've updated the package/directory name and now it works.

**Comment by aanm** [comment]
Steps to replicate:

```
cd k8s.io/code-generator
git checkout kubernetes-1.16.0-beta.2
mv _examples/apiserver/apis/example _examples/apiserver/apis/example.io
./generate-groups.sh all k8s.io/code-generator/_examples/apiserver/apis/example/client k8s.io/code-generator/_examples/apiserver/apis "example.io:v1"
```
output:
```
Generating deepcopy funcs
Generating clientset for example.io:v1 at k8s.io/code-generator/_examples/apiserver/apis/example/client/clientset
Generating listers for example.io:v1 at k8s.io/code-generator/_examples/apiserver/apis/example/client/listers
Generating informers for example.io:v1 at k8s.io/code-generator/_examples/apiserver/apis/example/client/informers
F0905 14:53:53.587509    8166 main.go:60] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/code-generator/_examples/apiserver/apis/example/client/informers/externalversions/example.io":
unable to format file "./k8s.io/code-generator/_examples/apiserver/apis/example/client/informers/externalversions/example.io/interface.go" (20:16: expected ';', found '.')
```
I think this PR might have introduced this PR https://github.com/kubernetes/kubernetes/pull/80440/

cc @sttts @munnerz @nikhita

**Comment by aanm** [comment]
@FxKu can you change the title to include `kubernetes-1.16.0-beta.2`? This is a regression in the library since it was working fine in `kubernetes-1.15.3`

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/kubernetes/pull/82410 to fix this

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/82410 and https://github.com/kubernetes/kubernetes/pull/83077 (will be present in v1.16.1)

/close

**Comment by FxKu** [comment]
Thanks a lot! #HappyFriday
