### ISSUE TITLE
Code generator generates incorrect package names

### ISSUE THREAD

**Issue by krzysztof-jastrzebski** [kubernetes/code-generator#80]
Code generator generates package names with dots which fails to compile.
The behavior has been changed by this commit:
https://github.com/kubernetes/code-generator/commit/5ac21ed6de7ac91d03e7917872c463de906d46a6#diff-9b57faef7d093e48f0c343f34da19a15
Before package names were first part of  group name and after change package names are equal to group names. This causes compilation errors as package names contain dots.

**Comment by nikhita** [comment]
Closing since this is a duplicate issue: https://github.com/kubernetes/kubernetes/issues/82860
Fix is in progress here: https://github.com/kubernetes/kubernetes/pull/82410

/close
