### ISSUE TITLE
I figured it out. I was missing the necessary tags in my API package.

### ISSUE THREAD

**Issue by yankunsam** [kubernetes/code-generator#81]
I figured it out. I was missing the necessary tags in my API package.

_Originally posted by @trstringer in https://github.com/kubernetes/code-generator/issues/38#issuecomment-381168167_

**Comment by yankunsam** [comment]
Can you give more detail information? I meet the same question.

**Comment by nikhita** [comment]
@yankunsam can you add more details about what problems you are facing and maybe even a reproducible case in the original issue? It's easier to track when all details are in the same issue so I'll close this one. :)

**Comment by yankunsam** [comment]
I try use code-generator to create listers, informers. And My test project is in https://github.com/yankunsam/tcontro. 
1. I run `./generate-groups.sh all  github.com/yankunsam/tcontro/pkg/generated github.com/yankunsam/tcontro/pkg/apis bar:v1alpha1`

2 the log message is `Generating deepcopy funcs
Generating clientset for bar:v1alpha1 at github.com/yankunsam/tcontro/pkg/generated/clientset
Generating listers for bar:v1alpha1 at github.com/yankunsam/tcontro/pkg/generated/listers
Generating informers for bar:v1alpha1 at github.com/yankunsam/tcontro/pkg/generated/informers`

3 but there is no "informers", "listers" directory.

**Comment by BassinD** [comment]
@nikhita, Help please. I have the same issue as described above.
