### ISSUE TITLE
how to add customized methods into expansion?

### ISSUE THREAD

**Issue by cofyc** [kubernetes/code-generator#84]
`expansion_generated.go` is auto-generated and will be overwritten. There is a way to fill customized methods into the interfaces?

**Comment by halfcrazy** [comment]
+1.  I want something like this.
 https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/node_expansion.go

**Comment by scuzhanglei** [comment]
@cofyc @halfcrazy hi guys, how did you fix this problem eventually?

**Comment by halfcrazy** [comment]
> @cofyc @halfcrazy hi guys, how did you fix this problem eventually?

I switched to use controller-runtime.

**Comment by cofyc** [comment]
I simply re-added my modifications. Anyway, I think it's worth supporting. 
/reopen
/remove-lifecycle rotten

**Comment by adamzhoul** [comment]
is support under consideration?
if not, the `expansion interface` is meaningless. 
especially code like:

```
type PodLister interface {
	List(selector labels.Selector) (ret []*v1.Pod, err error)
	Pods(namespace string) PodNamespaceLister
	PodListerExpansion
}

// PodListerExpansion allows custom methods to be added to PodLister.
type PodListerExpansion interface{}
```

 it's generated by lister-generator, and we shall not modify them.
 right? correct me if I am not.
