### ISSUE TITLE
generate-groups.sh requires GOPATH and does not honor GOBIN

### ISSUE THREAD

**Issue by porridge** [kubernetes/code-generator#87]
If one does not have `$GOPATH` set in the environment (which is not necessary with newer go versions), the script crashes with:
```
generate-groups.sh: line 71: GOPATH: unbound variable
```

Moreover, if one has `$GOBIN` set, the script does not honor that and tries to invoke the installed binaries from a wrong location.

**Comment by milosgajdos** [comment]
I have just tested this on 
```
go version go1.14 linux/amd64
```

With the following `go.mod` in my project
```
go 1.14

require (
	k8s.io/apimachinery v0.16.7
	k8s.io/client-go v0.16.7
	k8s.io/code-generator v0.16.7
)
```

And it still seems to be broken:
```
./vendor/k8s.io/code-generator/generate-groups.sh: line 71: GOPATH: unbound variable
```

**Comment by porridge** [comment]
@milosgajdos perhaps the fix is not in the version you specified. FWIW, [master](https://github.com/kubernetes/kubernetes/blob/5708511499fe500ae3b4bbd40204cef382f652e8/staging/src/k8s.io/code-generator/generate-groups.sh#L71) does not have any reference to `GOPATH` on line 71.

**Comment by milosgajdos** [comment]
Super strange!  I believe `go.mod` messed up my dependencies. I've now rectified this and it seems to be working as expected! Thanks @porridge
