### ISSUE TITLE
codegen on Windows use backslash

### ISSUE THREAD

**Issue by chrislinan** [kubernetes/code-generator#88]
Hi,
 when I run ./generate-groups.sh on my Windows, I got an error message:
W1126 17:22:17.589739   27540 import_tracker.go:46] Warning: backslash used in import path 'k8s_customize_controller\pkg\client\clientset\versioned\scheme', this is unsupported.

I found someone also met this problem in last year : https://github.com/kubernetes/sample-controller/issues/40

But I want to know, is there any fix for this issue? 

Thanks a lot.

**Comment by NiclasThobaben** [comment]
Are there any updates on this one?
We have the requirement to use the generator in developer environments on windows. We also haven't found a workaround yet.
