### ISSUE TITLE
how to use it with go modules?

### ISSUE THREAD

**Issue by gh67uyyghj** [kubernetes/code-generator#92]
Thank you for the project. How to use code-generator with Go projects after v1.11 depending on go.mod? I can't do the usual `go get` and there are no examples at all on how to use it.

**Comment by timdorr** [comment]
See the sample-controller for usage: https://github.com/kubernetes/sample-controller

They set up a dummy package called `tools` to do an import that will get it downloaded and vendorable: https://github.com/kubernetes/sample-controller/blob/master/hack/tools.go

**Comment by dvaldivia** [comment]
@timdorr I'm doing as suggested in `sample-controller` however, I keep getting error such as 
```
...
go: finding k8s.io/apimachinery v0.17.3
build k8s.io/code-generator: cannot load k8s.io/code-generator: no Go source files
##[error]Process completed with exit code 1.
```

or 

```
k8s/tools.go:20:8: build constraints exclude all Go files in /Users/dvaldivia/go/pkg/mod/k8s.io/code-generator@v0.17.3
```

Any idea how I can get it to play nice with other go modules?

**Comment by antoineco** [comment]
@dvaldivia you're not supposed to build that file or package. Notice the `// +build tools` constraint which cause that file to be ignored during builds. This idea is simply to have an explicit reference to your tools _somewhere_ in your code, so that Go considers them while resolving dependencies.
