### ISSUE TITLE
Failed to generate informers with goupName containing a dash

### ISSUE THREAD

**Issue by clementblaise** [kubernetes/code-generator#98]
Hello,
I'm using a group name containing a dash (ca-gip.github.com). I did not have any problems generating while using codegen v0.15.0.
But since I upgraded to newer version it's not possible anymore, I've tested with: v0.16.8, v0.17.0 and v0.17.4.
The error seems to be only associate to informers as clienset and listers are properly generated.

The log I get while using the update-codegen.sh script : 
```bash
resourcequotas-operator $ bash hack/update-codegen.sh 
Generating deepcopy funcs
Generating clientset for ca-gip:v1 at github.com/ca-gip/resourcequotas-operator/pkg/generated/clientset
Generating listers for ca-gip:v1 at github.com/ca-gip/resourcequotas-operator/pkg/generated/listers
Generating informers for ca-gip:v1 at github.com/ca-gip/resourcequotas-operator/pkg/generated/informers
F0320 14:10:32.749413   27566 main.go:60] Error: Failed executing generator: some packages had errors:
errors in package "github.com/ca-gip/resourcequotas-operator/pkg/generated/informers/externalversions/ca-gip":
unable to format file "/Users/clementblaise/go/src/github.com/ca-gip/resourcequotas-operator/pkg/generated/informers/externalversions/ca-gip/interface.go" (3:11: expected ';', found '-').
```

**Comment by clementblaise** [comment]
The client-gen is also affected by the same problems, at least for the fake parts.
I noticed that in pkg/generated/clientset/versioned/typed/ca-gip/v1/fake/fake_resourcequotaclaim.go it's using the group name without the dash. This result in a non working fake clientset since the real clientset is correctly generated with a dash in the group name.

Code Sample from generated/clientset/versioned/typed/ca-gip/v1/fake/fake_resourcequotaclaim.go
```go
// FakeResourceQuotaClaims implements ResourceQuotaClaimInterface
type FakeResourceQuotaClaims struct {
	Fake *FakeCagipV1
	ns   string
}

var resourcequotaclaimsResource = schema.GroupVersionResource{Group: "cagip.github.com", Version: "v1", Resource: "resourcequotaclaims"}

var resourcequotaclaimsKind = schema.GroupVersionKind{Group: "cagip.github.com", Version: "v1", Kind: "ResourceQuotaClaim"}
```
If I manually update the group like in the following code the fake clienset is working as expected :
```go
// FakeResourceQuotaClaims implements ResourceQuotaClaimInterface
type FakeResourceQuotaClaims struct {
	Fake *FakeCagipV1
	ns   string
}

var resourcequotaclaimsResource = schema.GroupVersionResource{Group: "ca-gip.github.com", Version: "v1", Resource: "resourcequotaclaims"}

var resourcequotaclaimsKind = schema.GroupVersionKind{Group: "ca-gip.github.com", Version: "v1", Kind: "ResourceQuotaClaim"}
```

**Comment by mdecalf** [comment]
The problem still exists and very problematic. We are blocked on v0.0.0-20190612205613-18da4a14b22b version of code generator ...

**Comment by efortin** [comment]
Hy Clement,

I've made the PR to fix it. Waiting review: [PR](https://github.com/kubernetes/code-generator/pull/127)

**Comment by cognifloyd** [comment]
I just ran into this issue with v0.23.4 so this is still valid

**Comment by pmalek** [comment]
Also encountered this issue when trying to move an api group `gateway-operator` from `api/` (as the core group) to be nested under `apis/`.

The problem specifically in my case was the import aliases:

```
F0629 12:29:08.119685   73975 main.go:65] Error: failed executing generator: some targets had errors: errors in target "github.com/kong/gateway-operator/pkg/clientset": unable to format file "pkg/clientset/clientset.go" (23:9: missing import path (and 6 more errors))
```

```
import (
	gateway-operatorv1alpha1 "github.com/kong/gateway-operator/pkg/clientset/typed/gatewayoperator/v1alpha1"
	gateway-operatorv1beta1 "github.com/kong/gateway-operator/pkg/clientset/typed/gatewayoperator/v1beta1"
...
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
    Gateway-operatorV1alpha1() gateway-operatorv1alpha1.Gateway-operatorV1alpha1Interface
	Gateway-operatorV1beta1() gateway-operatorv1beta1.Gateway-operatorV1beta1Interface
...
}
```

Trying to use `// +groupName=gateway-operator` and use `apis/gatewayoperator` dir didn't help.

**Comment by pmalek** [comment]
I managed to solve this using the 

```
// +groupGoName=gatewayoperator
```

code marker. Code ref: https://github.com/kubernetes/code-generator/blob/43d54fb5cb2cf7236fec3f8765ed37fb0eff0bef/cmd/client-gen/generators/client_generator.go#L362-L363
