### ISSUE TITLE
Failed making a parser 

### ISSUE THREAD

**Issue by BlackKD** [kubernetes/code-generator#99]
I'm trying to create a brand new apiserver using code-generator. So I create an empty golang project, and build this project 

![image](https://user-images.githubusercontent.com/13346479/77246200-c588ef00-6c5f-11ea-836d-db4737fb608f.png)

and project tree like:
![image](https://user-images.githubusercontent.com/13346479/77246208-e0f3fa00-6c5f-11ea-9297-f7901c5edb5a.png)

then I try to generator the code as follow

> cd $GOPATH/src/k8s.io/code-generator \
> && ./generate-groups.sh all \
> k8s_customize_controller/pkg/client \
> k8s_customize_controller/pkg/apis \
> bolingcavalry:v1

but got the error

> # ./generate-groups.sh all k8s_customize_controller/pkg/client >k8s_customize_controller/pkg/apis bolinDgcavalry:v1
>Generating deepcopy funcs
>F0322 16:00:18.366408   14906 main.go:82] Error: Failed making a parser: unable to add >directory "k8s_customize_controller/pkg/apis/bolinDgcavalry/v1": unable to import >"k8s_customize_controller/pkg/apis/bolinDgcavalry/v1": go/build: importGo >k8s_customize_controller/pkg/apis/bolinDgcavalry/v1: exit status 1
>can't load package: package k8s_customize_controller/pkg/apis/bolinDgcavalry/v1: malformed >module path "k8s_customize_controller/pkg/apis/bolinDgcavalry": missing dot in first path >element

**Comment by BlackKD** [comment]
I solved the problem:

need to bash the generate-groups.sh from project root  
![image](https://user-images.githubusercontent.com/13346479/77246320-06353800-6c61-11ea-87c0-cf8d66f0137c.png)

> [root@iZ2ze7b0axkx9hc5kpu14dZ k8s_customize_controller]# ./../k8s.io/code-generator/generate-groups.sh all k8s_customize_controller/pkg/client k8s_customize_controller/pkg/apis bolingcavalry:v1
> Generating deepcopy funcs
> Generating clientset for bolingcavalry:v1 at k8s_customize_controller/pkg/client/clientset
> Generating listers for bolingcavalry:v1 at k8s_customize_controller/pkg/client/listers
> Generating informers for bolingcavalry:v1 at k8s_customize_controller/pkg/client/informers


why not consider to add hints to remind users？

**Comment by yingzewen** [comment]
Can you tell me how you solved this problem ? thx

**Comment by lixiang233** [comment]
Just run `generate-groups.sh` in your CR's project root path @yingzewen
